src/main/resources/rs117/hd/vert.glsl

Fixes #5.
The problem is due to an uninitialised out parameter in `vert.glsl` when `fogDepth <= 0`. A simple else = 0 fixes the issue.

Fix setting None/Static fog to 0 causing broken rendering

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md

Due to the massive amounts of issues and feature requests coming in at the moment, it might be wise to use Runelite its issue templates. This pre-fills an issue with guidelines on how to report one properly.

Github issue templates

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/OpenCLManager.java
src/main/resources/rs117/hd/cl_types.cl
src/main/resources/rs117/hd/common.cl
src/main/resources/rs117/hd/comp.cl
src/main/resources/rs117/hd/comp_unordered.cl
src/main/resources/rs117/hd/priority_render.cl

This commit adds support for macOS by using OpenCL as an alternative to compute shaders. This matches the method used in RuneLite's GPU plugin, but accomodates some changes needed for normals calculation.

macOS support via OpenCL

---

src/main/java/rs117/hd/HdPlugin.java

Closes #100 
A while back, I made runelite/runelite#13795 for the core GPU plugin, to help let people know if their attempts at telling their computer to use the correct GPU was successful. It has come to my attention that it would also be useful in this project, even more so given the extra requirements HD has. It has also been tested on multiple different systems with multiple different combinations of dGPU and iGPU, and hasn't affected the loading of the plugin (those that couldn't before would still fail at the same place, which is after this modification)

gpu: display device and driver being used during plugin startup

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/HdPluginConfig.java

this adds a Range config to the brightness setting. So people can change the brightness better as theres 49 different values between 1 and 50. It sets the brightness value by dividing the int value with 20 so its between 0.05 and 2.5 and changing it by one changes the brightness by 0.05. Previously the lowest was 0.5 and highest was 1.5 so people can now put it alot lower which can be cool to see the lighting better and higher to see better in caves and  stuff. #83
Also it converts the old brightness setting to the new one so the brightness config wont reset after updating. I also tested this alot and it all works fine.

New brightness config

---

src/main/java/rs117/hd/lighting/NpcLight.java

As stated in the title, added new NpcLight definitions for the other two crossbow bolts that are present in the Hallowed Sepulchre.

Added NpcLight definitions for the other two crossbow bolts in the Hallowed Sepulchre.

---

runelite-plugin.properties

Adds the repo URL. Without the field, clicking Support takes you to the [latest commit (at time of submitting)](https://github.com/RS117/RLHD/tree/58772d5fc057c04b06eb6377ed85a70215153e32) instead of the [master page](https://github.com/RS117/RLHD).

Add support URL

---

src/main/java/rs117/hd/materials/ObjectProperties.java

Quick update to address the clutter of rocks in the Varrock path. Gray rocks now blend with the gray ground and tan rocks now blend more with the dirt path. Also textured a environment rock.

Improved Varrock path rocks and environment rock

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/HdPluginConfig.java
src/main/resources/rs117/hd/frag.glsl
src/main/resources/rs117/hd/shadow_frag.glsl
src/main/resources/rs117/hd/utils/fetch_material.glsl

Change from switch cases to nested ifs, and add a warning in case the workaround still crashes on M1 systems.
I also modified `MAX_MATERIALS` to match the list of materials instead of being hard-coded. Feel free to mention it if you want it reverted.
Thanks to @keyosk for pointing out the performance difference, and for testing it again on Intel MacOS.

Optimize MacOS Intel workaround

---

src/main/java/rs117/hd/GpuFloatBuffer.java
src/main/java/rs117/hd/GpuIntBuffer.java
src/main/java/rs117/hd/SceneUploader.java
src/main/java/rs117/hd/materials/Material.java

This mainly optimizes the performance of `SceneUploader.pushFace` which gets called a ton when there are many animated models on screen.
The main changes are:
* bulk buffer writes by exposing the underlying buffer's bulk methods
* simplifying material index lookup
The material index lookup was quite slow even with a hashmap just due the volume of calls. I simplified it to a primitive mapping of ints to ints but I would appreciate if somebody could check my assertions. 
I assumed that the `diffuseMapId` would never be greater than 10,000 or less than zero.
It is less than zero once for the `NONE` material but that case is handled correctly.
My framerate went from ~48 FPS before the patch to ~60FPS (capped) while standing in area with a lot NPCs.

optimize animated model pipeline

---

src/main/java/rs117/hd/materials/Material.java

was causing the "trapdoor" texture to be missing which resulted in a few bug reports

fix off by one texture lookup error

---

src/main/java/rs117/hd/config/ShadowResolution.java

This PR simply adds an "extreme" shadow resolution option. It does significantly increase GPU (+20%) and VRAM (+760MiB) usage on my 1660ti but users with high end systems might find the GPU usage acceptable for significantly crisper shadows when used with max shadow distance.  Thanks to Aeryn for the suggestion and help implementing/testing.

add 16384 shadow resolution

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/environments/EnvironmentManager.java

This PR makes it to where the scene is reloaded whenever the player: enters a house, changes floors in the house, interacts with parts of the UI in a house, and maybe other things in a house. I noticed that client var 384 changing correlated with the performance decreases in POH. So this simply reloads the scene if that client var changes while the player is in a house. In my testing this totally fixes the POH performance problems on my machine. I also slightly refactored the way scene reloading works because I was inconsistently crashing with the old method with this fix.
Shoutout to Hooder, Keyosk, and everyone else in the RLHD Discord for helping me track this down :smile:

dynamically reload POH scene

---

src/main/java/rs117/hd/HdPlugin.java

This ports GPU plugin commits https://github.com/runelite/runelite/commit/bb43d232bb594c6e062e3342fa7db1b53f594c11 and https://github.com/runelite/runelite/commit/637ee563d622fa187b2e4537ade86979bad1dbc9.
All credits for these fixes go to Adam.

Port GPU plugin fixes for stretched mode on MacOS

---

src/main/java/rs117/hd/SceneUploader.java

The addition of the Winter Theme rolled back one of the fixes in #167. The fix allowed tiles to use their vanilla colours unless using the Ground configs (Textures and/or Blending). With the addition of the Winter Theme, tile recolouring now occurs even with all Ground options disabled.
This PR adds a final check for `configWinterTheme` before applying tile recolouring. With `configGroundTextures`, `configGroundBlending` and `configWinterTheme` disabled, tiles will correctly use their vanilla colours.
Closes #196 .

Preserves vanilla tile colours when Ground configs are disabled

---

src/main/java/rs117/hd/HdPlugin.java

Apparently on some M1 systems, the following warning is thrown (once) when no texture is bound to the `shadowMap` sampler:
```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
```
See Discord for confirmation:
https://discord.com/channels/886733267284398130/887408540988350475/917896872381788190
This is largely unnecessary to fix, but may save some developer's time in the future, as the error message is somewhat misleading.

Bind dummy shadow map texture when shadows are disabled

---

src/main/resources/rs117/hd/priority_render.glsl

Fixes #209
It seems like there's some undefined behavior with Nvidia and too many branches. The return at the bottom of the switch statement doesn't appear to be getting called.

Refactor count_prio_offset method to reduce branches

---

src/main/java/rs117/hd/HdPlugin.java

One of the first steps we ask users in the Windows support channel to do is post their logs and to open task manager and check if they're running 32-bit or 64-bit Runelite. This eliminates a step by logging the info we're looking for.
```
[Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
[Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 511.23
[Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
```

log client arch

---

src/main/java/rs117/hd/FixedLengthHashCode.java
src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/HdPluginConfig.java
src/main/java/rs117/hd/ModelPusher.java
src/main/java/rs117/hd/SceneUploader.java
src/main/resources/rs117/hd/cl_types.cl
src/main/resources/rs117/hd/comp.glsl

This is a pretty big PR but it's been well tested by members of the Discord (shoutout to Aeryn for helping me iterate on this).  
I did a big refactor to the way model pushing is done to make the logic much clearer. Doing so allowed me to pick out the slowest part of the process (calculating colors) and add caching that should greatly improve performance for most systems. I made a config option for this but I enabled it as the default since I estimate the additional ram usage to be pretty low at around 50MB on average.
To resolve the turing/ampere artifacting I changed some logic that I suspect was corrupting data and ported Adam's [unused MAX_TRIANGLE increase](https://github.com/Adam-/runelite/commit/8cd6c296f4b150f84649218bb9735161359c506c).

Fix nvidia artifacting and add partial model caching

---

src/main/resources/rs117/hd/priority_render.cl
src/main/resources/rs117/hd/priority_render.glsl

Thanks to Adam for this refactor
https://github.com/Adam-/runelite/commit/bc5beb5304eb0b911538d558dd433bf09cd04b9c
I've tested this on a 2019 MBP with AMD dGPU, and a 2013 MBP With Nvidia dGPU, and Intel Iris Pro iGPU.

opencl: replace count_prio_offset switch with loop

---

src/main/java/rs117/hd/ModelPusher.java

This makes allocations dramatically slower with caching enabled. With cache disabled allocations are still a little fast but much less extreme than they were before. Both with/without cache see significant performance gains in heavy scenes from this.

reduce allocations in model pushing

---

src/main/java/rs117/hd/HdPlugin.java

Closes #172 and #188.
I haven't playtested this a lot, but I think this widget should be reliable.
Arguably the bug might be better off fixed internally within RuneLite, as there is already code for getting the viewport offset, but it's currently broken for cutscenes in resizeable mode. This is currently broken in the regular GPU plugin as well.

Fix cutscene viewport offsets in resizeable mode

---

src/main/java/rs117/hd/HdPluginConfig.java

There are 7 changes here, some may not be wanted but i thought i would post them to get some opinions and discussion going. 
If you are in favor or against anything in particular, post a comment.
Here's what i changed and why:
AA description:
A little bit clearer IMO. The warning about 8x/16x may help some people who are unintentionally maxing out their GPU's and information is added about this specifically being GPU load - the CPU is practically unaffected.
AF description:
Specifies that the range is from 0 to 16x. This is not otherwise obvious and because the setting is a box rather than a dropdown, some people aren't aware that they can/should set it higher.
AF default of 16x, up from 1x:
I'm not sure if there is a good reason that we can't do this, however 16x AF is visually impactful …

Update default config & descriptions

---

src/main/java/rs117/hd/ModelPusher.java

User c-pin in the Discord [uploaded](https://discord.com/channels/886733267284398130/886739001837498418/945203601729544203) a `client.log` of a crash that seems to be caused by hash collision of two models with different vertex counts. Given that hash collisions seem to be very rare this simply gets fresh data if the cached data has a different face count than the model.
Despite being unable to reproduce the crash I'm fairly certain this will prevent it from happening.

prevent ArrayIndexOutOfBoundsException on hash collision

---

src/main/java/rs117/hd/HdPlugin.java

This reintroduces https://github.com/runelite/runelite/commit/6f5735be077e74e3790b9163bcf8d2684eedbb00
But with the logic fixed so that shadows can be drawn while the loading is happening as well. I believe this also fixes the screen flickering that some users have reported during loading. https://github.com/RS117/RLHD/issues/199 in particular seems to be fixed by these changes.

draw loading and connection lost boxes

---

src/main/java/rs117/hd/HdPlugin.java

Addresses #210 
I was able to reproduce the bug with the following steps:
1) log in
2) log out
3) suspend computer for 1 minute
4) log in
The effects seems kind of random. This is what it [looked like](https://cdn.discordapp.com/attachments/886739974555316294/945196921000173629/suspend-glitch.png) on one attempt.

fix buffer corruption after OS suspend

---

src/main/java/rs117/hd/HdPlugin.java

This commit works around a bug with loading natives when the user's home folder contains special characters such as `&`, `^` or `!`. For further details, see the PR over at runelite/runelite#14712.

Fix loading gluegen natives on some Windows configurations

---

src/main/java/rs117/hd/HdPlugin.java

Prevents the flashing effect that occurs in resizable mode when logging in.
supersedes/closes #229

Don't use skybox color until after the first logged in GameTick

---

src/main/resources/rs117/hd/shadow_frag.glsl

Objects are prevented from casting shadows if their transparency is below X threshold.
If this threshold is too low, semitransparent objects may cast shadows when they're not supposed to or animated objects with variable transparency may cast shadows for part of their animation but not the rest of it - thus causing sharp strobing shadows.
If the threshold is too high, some objects which are supposed to cast shadows do not.
This was previously discussed in https://github.com/RS117/RLHD/issues/56 and the threshold was bumped from 0.25 to 0.3 to fix this specific case, but i continued to experiment and discuss other cases since then.
I've made a spreadsheet of affected objects here - https://docs.google.com/spreadsheets/d/16UIcbYeTgiubOE6nnOTjvZRabG80ZuxxPxFTIcLfnwY/edit#gid=0. Most things …

Improve shadow threshold

---

src/main/resources/rs117/hd/lighting/lights.json

This adds lighting in to the center of each of the 3 Cerberus Lairs, as well as the Soul Devourer, and the fires around the room
Before:
After:

Add Cerberus Lair lighting

---

src/main/java/rs117/hd/lighting/Light.java
src/main/java/rs117/hd/lighting/LightConfig.java
src/main/java/rs117/hd/lighting/LightManager.java
src/main/resources/rs117/hd/lighting/lights.json
src/test/java/rs117/hd/lighting/ExportLightsToJson.java
src/test/java/rs117/hd/lighting/LightConfigTest.java
src/test/resources/lighting/lights.json

- Move config loading into a separate class, for ease of use from different places.
- Add `equals` and `hashCode` methods to `Light` class for removing duplicates.
- Make `ExportLightsToJson` read lights from both old and new formats, and combine the results into a JSON file with no duplicates.
- Make `ExportLightsToJson` convert NpcIDs and ObjectIDs to field names where possible.
Note: field names are likely to change in RuneLite more frequently than their IDs, so at some point it might make sense to revert to using only IDs again, and instead use other tooling to modify lights.
I've decided not to include the newly generated `lights.json` file, and instead leave that up to maintainers, since it might mess with diffs from other PRs.

Add support for NpcID and ObjectID names in light config

---

src/main/resources/rs117/hd/lighting/lights.json

Shilo gem mine lighting

---

build.gradle
src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/OpenCLManager.java

This wraps the `GL4` instance in `DebugGL4` when the plugin is turned on while debug logging is enabled, if it is present on the classpath. When launching HD through `HdPluginTest`, `DebugGL4` is added to the classpath by Gradle.
Why? [`DebugGL4`](https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/opengl/DebugGL4.html) intercepts all GL calls and checks if OpenGL reported an error after the call, and if so, it throws an exception. This can be quite helpful with tracking down invalid GL calls that otherwise go unnoticed.
Depends on #261

Enable DebugGL when running with debug logging

---

src/main/java/rs117/hd/SceneUploader.java

This fixes #166
I can't imagine this is the right approach, but perhaps it'll inspire someone to make a good fix.
Before:
After:

Shilo bridge texture adjustment - fixes #166

---

src/main/resources/rs117/hd/lighting/lights.json

Adds lights for objects in the Land of the Goblins quest & Hopespear's Will miniquest.

Lights for Land of the Goblins quest

---

src/main/java/rs117/hd/HdPluginConfig.java
src/main/java/rs117/hd/environments/Environment.java
src/main/java/rs117/hd/environments/EnvironmentManager.java
src/main/resources/rs117/hd/lighting/lights.json

Currently the environments force specific skybox colors if they are defined, overriding the menu option. This PR adds a checkbox to force the color selected in the menu instead.
It is selectively applied so that areas which need a specific skybox for game or quest design (such as black for empty space at the cosmic altar) can still force their values, but the vast majority of the game world will obey the menu if enabled.
Fixes #205

Override environment sky option

---

src/main/java/rs117/hd/HdPlugin.java

This fixes two very rare race conditions. Sometimes loading OSRS (via RuneLite with RLHD enabled) and clicking the settings button too quickly, there is an NPE where getGraphics returns null. 
You can see getGraphics returns null in a few situations: 
After fixing this, it then exposes a GLException (again, when loading via RuneLite with RLHD enabled) where it fails to swap buffers.
Again, you can see that swapBuffers throws GLException, yet we aren't currently handling that exception so if it throws that exception, it crashes RuneLite entirely (even though it's a recoverable problem by simply resetting the plugin): 
I can see we have very similar handling of an exception right here: https://github.com/RS117/RLHD/blob/master/src/main/java/rs117/hd/HdPlugin.java#L1661 and we also reset the …

Fix rare race conditions with graphics/swapBuffers

---

build.gradle
src/main/java/rs117/hd/HdPlugin.java

This prevents gluegen from testing if the tempdir is noexec, resulting
in it always using the tempdir. The test seems unreliable since we see
many users who fail the exec test but the plugin would work for
otherwise.

set jogamp.gluegen.TestTempDirExec=false

---

src/main/java/rs117/hd/HdPlugin.java

This fixes a bug introduced by 81a9886e3cc473e6ae3a2e2f57f869ae1d852ad0 where the plugin will continuously attempt to restart itself indefinitely if the plugin had been turned off for longer than a minute. This fixes the bug by also updating `lastFrameTime` in `startUp()`.

Fix plugin startup loop bug

---

src/main/resources/rs117/hd/shadow_frag.glsl

Have to bump this down from 0.85 to 0.81 so that one of the new objects in GOTR works properly.
https://docs.google.com/spreadsheets/d/16UIcbYeTgiubOE6nnOTjvZRabG80ZuxxPxFTIcLfnwY/edit#gid=0
Will add a tick or two of shadows to the aberrant spectre animation. No great setting for this but i think this value is least-bad for now.

Update shadow threshold

---

src/main/java/rs117/hd/HdPluginConfig.java

We're now 3 days into northern hemisphere spring, ~7/8'ths of people live there.
When this setting was created it was enabled for everybody, should we reset it to be turned off for everybody or only change the default for new plugin users?

Disable default winter theme

---

src/main/java/rs117/hd/lighting/Light.java
src/main/java/rs117/hd/lighting/LightConfig.java
src/main/java/rs117/hd/lighting/SceneLight.java
src/main/resources/rs117/hd/lighting/lights.json
src/test/java/rs117/hd/lighting/ExportLightsToJson.java
src/test/java/rs117/hd/lighting/LightConfigTest.java
src/test/resources/lighting/lights.json

This converts color values from linear color space in the range [0, 1] into gamma color space in the range [0, 255] to make manually configuring light colors in the JSON config more intuitive, matching values from a typical color picker. The numbers are still floats, so decimals are still supported, but I figured I would also strip unnecessary decimals in the conversion process, leaving color values looking more like those in the old formats. Colors are still in linear color space after they've been loaded from the JSON.
Summary of changes:
- Changes to `ExportLightsToJson`:
- Add various command line arguments (e.g. `--dry-run` option for testing).
- Error when more than 3 color values are provided, since the alpha channel is currently unused.
- Error when all 3 values of a color are …

Switch to using the more intuitive gamma color space for configuring lights

---

src/main/resources/rs117/hd/lighting/lights.json

Adjust the red Darkmeyer street lamp so that it reaches the ground, nearby buildings and objects more effectively. Also changes the light color to be a bit whiter than pure red.
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=dad7fb3a-c98c-11ec-b5bb-6595d9b17862
"Solid improvement, really adds to the ambiance!" - Keyosk
"i love it" - breakthetargets

Tweak lamp

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/config/DefaultSkyColor.java
src/main/java/rs117/hd/environments/EnvironmentManager.java

Trigger a sky color update when the Skybox plugin's config changes, if the current sky is set to use RuneLite's skybox. This is done in `onBeforeRender` with a lower priority so it runs after the Skybox plugin updates its sky color. Maybe there's a better way to go about this, but I'm not sure.
Other changes:
- I've changed the default back to blue after it was changed to RuneLite's skybox in connection with #288, since it fits a lot better with HD than the Skybox plugin's default color. Ideally, this would be added to runelite/plugin-hub#2638 so we don't change the default away from blue in the live version.
HD Blue:
Skybox plugin's default:
- I've also changed the logic for applying water color slightly. Now it applies color also from the default sky, unless it's set to `OSRS` (which is …

Update sky color whenever the skybox plugin config is changed

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/HdPluginConfig.java

Fix auto-reloading of the scene when the winter theme setting is toggled. Also moves the setting to the miscellaneous section.

Fix winter theme auto-reload

---

src/main/java/rs117/hd/data/materials/Overlay.java

This is most noticeable in low detail mode.
Before:
After:

Fix misplaced water tiles in Temple of the Eye

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/opengl/compute/OpenCLManager.java

Avoid crashes during cleanup in the event of a crash during startup. This currently leads to having to restart the whole client whenever shader compilation fails.
Also removes an incorrect import depending on RuneLite's GPU plugin.

Fix cleanup after compilation error & other minor fixes

---

src/main/resources/rs117/hd/scene/lighting/lights.json

Working code that implements the feature I proposed in https://github.com/RS117/RLHD/issues/308#issue-1244055520!
Added the Lit Brazier to lights.json
```JSON
{
"description": "WINTERTODT_LIT_BRAZIER",
"height": 300,
"alignment": "CENTER",
"radius": 600,
"strength": 15,
"color": [
165,
255,
56
],
"type": "FLICKER",
"duration": 0,
"range": 15,
"objectIds": [
"BURNING_BRAZIER_29314",
"BURNING_BRAZIER_31926"
]
},
```
https://github.com/Ben10164/RLHD/blob/9cb635344aa8b423caefeb6bef441d70684727f7/src/main/resources/rs117/hd/scene/lighting/lights.json#L29331-L29349
As well as moving the *Doors of Dihn* down to follow the Lit Brazier
```JSON
{
"description": "WINTERTODT_DOOR",
"height": 500,
"alignment": "SOUTH",
"radius": 1500,
"strength": 15,
"color": [
165,
255,
56
],
"type": "STATIC", …
```

Added the lit Braziers in Wintertodt as a light source

---

src/main/java/rs117/hd/data/environments/Area.java
src/main/java/rs117/hd/data/materials/Overlay.java

Tile blending was broken with the fancy pattern in front of the GOTR entrance/exit portal. I had no idea how to fix this before but turns out it's relatively simple and there is precedence elsewhere for loads of similar fixes.
Without ground blending:
With ground blending before fix:
With ground blending after fix:

Fix GOTR Entrance

---

src/main/java/rs117/hd/data/environments/Area.java
src/main/java/rs117/hd/data/materials/Overlay.java

Disables tile blending on some of the path leading to East Ardy's castle+bridge and all of the dirt immediately surrounding the castle to remove many tile blending artifacts. The area seems particularly vulnerable to them because of a lot of lumpy and sloped terrain with mixed tile types.
Also adjusted lightness to approx correct values so that things don't have seams or look unusual. They are area-based property adjustments so it's pretty easy to look over each affected tile, all looks good to me

East Ardy castle tile blending fix

---

src/main/java/rs117/hd/scene/lighting/LightManager.java

Teleporting to here Crashed the client
As some light was showing the plane as -1, to fix this I made the change of if the TileZ is -1 or under it defaults to 0 to be safe, this is a bad crash as it happens in the wildy

Light Crash Fixes

---

src/main/java/rs117/hd/scene/lighting/LightManager.java

Adam said its not needed as npcs are never on "-1" where objects can be EG: Underside of bridges

Removed the check for npcs on -1
