RS117/RLHD

src/main/java/rs117/hd/environments/Area.java
src/main/java/rs117/hd/materials/Overlay.java

Closes https://github.com/RS117/RLHD/issues/63
New area mess hall has been created.

fix(mess_hall): correct overlay for kitchen floor tiles

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/HdPluginConfig.java
src/main/java/rs117/hd/ProceduralGenerator.java

Add the ability to toggle ground/tile blending.
This would close #76 
Preview: 
https://gyazo.com/f761b99b4ea5a6553dba0bdf84297082

Add Ground Blending option to configuration

---

README.md

Adds an icon and links to Discord server and Twitter.

Add icon and links to readme

---

src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/SceneUploader.java

Ported from [this commit](https://github.com/runelite/runelite/commit/37608d1e6451491ec27d5b5dede2117baeedb54b#diff-84afc01bb90bb0f7736b623bcf51caba4480a9f09c7f62b4effb931b915fb3de) to the GPU plugin. I also [made a small readability refactor](https://github.com/RS117/RLHD/pull/173/files#diff-9d6aeed4ff0e55264978ec6b160c6610a3b2c9d28b2a4ae653fe2a26ee534d53R2320) that get's the model and does the null check sooner.

port improved model visible check

---

build.gradle
src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/HdPluginConfig.java

Full credit to Adam for this improvement: https://github.com/runelite/runelite/commit/13ecfc0a9eaf3161b979f6e9f1b6f66fa075fb51

VSync Configuration

---

src/main/java/rs117/hd/GpuIntBuffer.java
src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/SceneUploader.java

This refactor yields significant FPS gains in many areas on my system with poor single core performance. The meat of this PR is just a replacement of `pushFace` with `pushModel` which allows reduction of a lot of model related overhead in the main face pushing loop. I suspect that the new `pushModel` method can be further refined in the future but it's in a pretty good state now. :smile:

Refactor model pushing

---

src/main/java/rs117/hd/lighting/LightManager.java

all credit to @aHooder for this one :)

remove flickering light frame dependence

---

src/main/java/rs117/hd/HdPlugin.java

Port of https://github.com/runelite/runelite/commit/2e34cbc
All credits go to Adam.

(Port from GPU) Reset fbo on ResizableChanged on macOS

---

src/main/java/rs117/hd/HdPlugin.java

Revert "Fix cutscene viewport offsets in resizeable mode"

---

src/main/java/rs117/hd/HdPlugin.java

- request the GL4 profile instead of GL default because some drivers default to really old OpenGL and it causes a crash
- catch exceptions that happen here and try to shut down the plugin to prevent a hard crash
- don't request the gl profile multiple times because we might use a version that is different from what we reported

simplify startup logic and try to prevent crashing from driver issues

---

src/main/resources/rs117/hd/lighting/lights.json

Updated to work with Hooder's JSON change
Looks good to me, played with a bunch of values; feedback is appreciated though.
https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=6e910cfe-9d8c-11ec-b5bb-6595d9b17862

Aberrant/Abhorrent Spectre lights

---

src/main/resources/rs117/hd/lighting/lights.json

improve camdozaal lighting

---

src/main/resources/rs117/hd/lighting/lights.json

Same style as the green ones
https://streamable.com/9o45rh
The superior one has a different color and unique purple outline as seen here - https://www.youtube.com/watch?v=dIwwgEFHViY - so i wasn't quite sure what to do with it. I set a flat purple glow for now.

Deviant/Repugnant Spectre lights

---

build.gradle
src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/lighting/LightManager.java

Fixed #123,#134 also added blocking for Projectile lights and normal npcs

Hide Lights

---

build.gradle
src/main/java/rs117/hd/HdPlugin.java
src/main/java/rs117/hd/OpenCLManager.java

This cherry-picks Adam's commit 90359fa onto master.

Update to 1.8.14-SNAPSHOT

---

src/main/java/rs117/hd/HdPlugin.java

Related:
https://github.com/runelite/runelite/pull/14749
https://github.com/runelite/runelite/issues/12930

Fixes draw frame npe

---

src/main/resources/rs117/hd/lighting/lights.json

Refine Spectre lights

---

src/main/java/rs117/hd/materials/ObjectProperties.java

Add missing tile for TzHaar recolor

---

src/main/resources/rs117/hd/lighting/lights.json

Game object reused hundreds of times @ fire altar

Remove bad light

---

src/main/java/rs117/hd/data/materials/Overlay.java

Fixes the blood lake at the true blood altar to be water instead of dirt, hopefully doesn't break anything else
Big thx to @aHooder

Add blood water

---

src/main/java/rs117/hd/data/environments/Area.java
src/main/java/rs117/hd/data/materials/Overlay.java

Fix Gu'tanoth cave water

---

src/main/resources/rs117/hd/scene/lighting/lights.json

Quick pass to add lights here (mostly copy/pasted from similar Karuulm objects and adjusted). Torches were already lit in above pic but it shows all of the other new ones (lava vents, holes and the lava itself to cast light on nearby objects and hide those ugly shadows)

Fossil Island lava lights

---

build.gradle
src/main/java/rs117/hd/data/BakedModels.java

Baked models foundry
